# Generated by Django 3.1 on 2023-11-24 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='date_pub',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
    ]
